- name: play level variables
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
    ansible.bultin.debug:
      msg: "Course Name is: {{ COURSE }}, Duratioin: {{ DURATION }}, Trainer:{{ Trainer }}"